cc_binary(
    name = "part1_main",
    srcs = ["part1_main.cc"],
    data = ["//advent/day1:files"],
    deps = [
        "@com_google_absl//absl/flags:flag",
        "@com_google_absl//absl/flags:parse",
        "@com_google_absl//absl/strings",
    ],
)
